version: "3"

services:
  prom:
    image: prom/prometheus:v2.15.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter:v0.18.1
  pushgateway:
    image: prom/pushgateway:v1.0.1
    ports:
      - "9091:9091"

