version: "3"

services:
  jobmanager:
    image: flink:1.9.1
    ports:
      - "8081:8081"
    network_mode: "host"
    command: jobmanager
    volumes:
      - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar
      - ./lib/flink-metrics-prometheus-1.9.0.jar:/opt/flink/lib/flink-metrics-prometheus-1.9.0.jar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_ENV_JAVA_OPTS=-Dlog.file=/opt/flink/log/jobmanager.log

  taskmanager:
    image: flink:1.9.1
    depends_on:
      - jobmanager
    command: taskmanager
    network_mode: "host"
    # deploy:
    #   replicas: 2
    volumes:
      - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar
      - ./lib/flink-metrics-prometheus-1.9.0.jar:/opt/flink/lib/flink-metrics-prometheus-1.9.0.jar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_ENV_JAVA_OPTS=-Dlog.file=/opt/flink/log/taskmanager.log

  prom:
    image: prom/prometheus:v2.15.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.5.3
    ports:
      - "3000:3000"
