# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'

services:

  ghost:
    image: ghost:3
    restart: always
    ports:
      - 80:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: foo_password
      database__connection__database: ghost

  db:
    image: mysql:5.7.28
    restart: always
    volumes: 
      - '/var/lib/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: foo_password