version: "3"

services:
  jobmanager:
    image: flink:1.9.1
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./conf/log4j.properties:/opt/flink/conf/log4j-console.properties
      - ./lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_ENV_JAVA_OPTS=-Dlog.file=/opt/flink/log/jobmanager.log
  taskmanager:
    image: flink:1.9.1
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./conf/log4j.properties:/opt/flink/conf/log4j-console.properties
      - ./lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_ENV_JAVA_OPTS=-Dlog.file=/opt/flink/log/taskmanager.log